name: Extract RER A GTFS export

on:
  schedule:
    - cron: "3 3 * * *" # chaque jour à 3h03 UTC
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run extraction script
        run: python3 ./scripts/extract_rer_a_gtfs.py

      - name: Commit & push export
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add static/rer_a_prochains_trains_by_direction.json
          git commit -m "Auto: maj horaires RER A" || echo "no change"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
