name: Auto GTFS RER A Extract

on:
  schedule:
    - cron: "0 2 * * *"    # chaque nuit à 2h (UTC)
  workflow_dispatch:       # lancement manuel possible

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install pandas requests

      - name: Run GTFS extraction script
        run: python3 ./scripts/extract_rer_a_gtfs.py

      - name: Commit export if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add static/rer_a_prochains_trains.json
          git commit -m "Mise à jour auto horaires RER A GTFS" || echo "Pas de modif"
          git push
