name: Mise à jour horaires RER A – Joinville-le-Pont

on:
  schedule:
    # Tous les jours à 04 h UTC ≈ 06 h Paris
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Proxy incluant déjà ?url=
      PROXY_WORKER: "https://ratp-proxy.hippodrome-proxy42.workers.dev/?url="
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python script.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github"
          if git status --porcelain | grep -q "data/today.json"; then
            git add data/today.json
            git commit -m "maj horaires $(date +%F)"
            git push
          else
            echo "Pas de changement"
          fi
