name: Update GTFS stops

on:
  schedule:
    - cron: '0 3 * * 1' # Chaque lundi à 3h
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install pandas requests
      - name: Générer gtfs-stops-full.json
        run: python3 ./scripts/gtfs_extract.py
        env:
          IDFM_APIKEY: ${{ secrets.IDFM_APIKEY }}
      - name: Commit & push si changé
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add static/gtfs-stops-full.json
          git diff --cached --quiet || git commit -m "Màj GTFS stops full auto"
          git push
